# Generated by Django 2.0.7 on 2018-07-28 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Source', models.CharField(max_length=100)),
                ('Destination', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('StatusText', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xmlns_process', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Header')),
                ('Process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Process')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procees_from', models.CharField(max_length=100)),
                ('ticket_id', models.CharField(max_length=100)),
                ('change_request', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='process',
            name='ticket_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Ticket'),
        ),
    ]
